<?php
if (!defined('ABSPATH')) {
    exit; // Exit if accessed directly
}
?>
<div id="lead-form-modal" class="modal">
    <div class="modal-content">
        <span class="close">&times;</span>
        <h2>Lead Details <span class="required-note">(Compulsory fields are marked with red*)</span></h2>
        
        <form id="leadForm" class="lead-form">
            <div class="form-row">
                <div class="form-group">
                    <label for="leadGeneratedBy">Lead Generated By <span class="required">*</span></label>
                    <select id="leadGeneratedBy" name="lead_generated_by" required>
                        <option value="">Select Lead Generated By</option>
                        <?php
                        // Get sales team members
                        $sales_team = get_users(['role' => 'sales']);
                        foreach ($sales_team as $member) {
                            echo '<option value="' . esc_attr($member->ID) . '">' . esc_html($member->display_name) . '</option>';
                        }
                        ?>
                    </select>
                </div>
                
                <div class="form-group">
                    <label for="companyName">Company Name <span class="required">*</span></label>
                    <input type="text" id="companyName" name="company_name" placeholder="Client Name" required>
                </div>
                
                <div class="form-group">
                    <label for="clientType">Type <span class="required">*</span></label>
                    <select id="clientType" name="client_type" required>
                        <option value="">Select Client Type</option>
                        <option value="Sign Maker">Sign Maker</option>
                        <option value="Printer">Printer</option>
                        <option value="Ad Agency">Ad Agency</option>
                    </select>
                </div>
            </div>

            <div class="form-row">
                <div class="form-group">
                    <label for="email">Email <span class="required">*</span></label>
                    <input type="email" id="email" name="email" placeholder="Email" required>
                </div>
                
                <div class="form-group">
                    <label for="status">Status <span class="required">*</span></label>
                    <select id="status" name="status" required>
                        <option value="">Select Status</option>
                        <option value="new">New</option>
                        <option value="in-progress">In Progress</option>
                        <option value="qualified">Qualified</option>
                        <option value="unqualified">Unqualified</option>
                    </select>
                </div>
            </div>

            <div class="form-row">
                <div class="form-group">
                    <label for="website">Website</label>
                    <input type="url" id="website" name="website" placeholder="Website">
                </div>
                
                <div class="form-group">
                    <label for="assignTo">Assign to</label>
                    <select id="assignTo" name="assign_to">
                        <option value="">Select Sales Person Name</option>
                        <?php
                        foreach ($sales_team as $member) {
                            echo '<option value="' . esc_attr($member->ID) . '">' . esc_html($member->display_name) . '</option>';
                        }
                        ?>
                    </select>
                </div>
            </div>

            <h3>Address:</h3>
            
            <div class="form-row">
                <div class="form-group">
                    <label for="country">Country</label>
                    <select id="country" name="country">
                        <option value="India">India</option>
                    </select>
                </div>
                
                <div class="form-group">
                    <label for="zone">Zone <span class="required">*</span></label>
                    <select id="zone" name="zone" required>
                        <option value="">Select Zone</option>
                        <option value="north">North</option>
                        <option value="south">South</option>
                        <option value="east">East</option>
                        <option value="west">West</option>
                    </select>
                </div>
                
                <div class="form-group">
                    <label for="state">State <span class="required">*</span></label>
                    <select id="state" name="state" required>
                        <option value="">Select State</option>
                        <!-- States will be populated via JavaScript based on zone selection -->
                    </select>
                </div>
                
                <div class="form-group">
                    <label for="city">City <span class="required">*</span></label>
                    <select id="city" name="city" required>
                        <option value="">Select City</option>
                        <!-- Cities will be populated via JavaScript based on state selection -->
                    </select>
                </div>
            </div>

            <div class="form-row">
                <div class="form-group full-width">
                    <label for="address">Address <span class="required">*</span></label>
                    <input type="text" id="address" name="address" placeholder="Address" required>
                </div>
            </div>

            <div class="form-row">
                <div class="form-group">
                    <label for="zipCode">Zip Code</label>
                    <input type="text" id="zipCode" name="zip_code" placeholder="Zip Code" pattern="[0-9]{6}" title="Please enter a valid 6-digit zip code">
                </div>
            </div>

            <div class="form-actions">
                <button type="submit" class="btn submit">Submit</button>
                <button type="reset" class="btn reset">Reset</button>
                <button type="button" class="btn cancel">Cancel</button>
            </div>
        </form>
    </div>
</div>