<?php
if (!defined('ABSPATH')) {
    exit;
}

$lead_id = isset($_GET['lead_id']) ? intval($_GET['lead_id']) : 0;
$is_edit = !empty($lead_id);

global $wpdb;
$leads_table = $wpdb->prefix . 'pipeline_leads';

$lead = null;
if ($is_edit) {
    $lead = $wpdb->get_row($wpdb->prepare(
        "SELECT * FROM $leads_table WHERE id = %d",
        $lead_id
    ));
    
    if (!$lead) {
        wp_die('Lead not found');
    }
}

$users = \CoSignPlanner\cosign_get_users_list();
?>
<style>
:root {
    --primary-color: #000066;
    --secondary-color: #92b92a;
    --text-color: #2c3e50;
    --light-gray: #f8f9fa;
    --border-color: #e2e8f0;
    --shadow: 0 2px 4px rgba(0,0,0,0.1);
    --transition: all 0.3s ease;
    --radius: 8px;
}

.wrap.cosign-wrap {
    max-width: 1200px;
    margin: 2rem auto;
    background: white;
    border-radius: var(--radius);
    box-shadow: var(--shadow);
}

.cosign-header {
    background: linear-gradient(135deg, var(--primary-color), #000099);
    color: white;
    padding: 1.5rem 2rem;
    border-radius: var(--radius) var(--radius) 0 0;
    display: flex;
    justify-content: space-between;
    align-items: center;
}

.cosign-header h1 {
    margin: 0;
    font-size: 1.75rem;
    font-weight: 600;
}

.cosign-form {
    padding: 2rem;
}

.cosign-form-row {
    margin-bottom: 1.5rem;
}

.cosign-form-row label {
    display: block;
    margin-bottom: 0.5rem;
    color: var(--text-color);
    font-weight: 600;
    font-size: 0.95rem;
}

.cosign-form-row input[type="text"],
.cosign-form-row input[type="email"],
.cosign-form-row input[type="tel"],
.cosign-form-row input[type="url"],
.cosign-form-row select,
.cosign-form-row textarea {
    width: 100%;
    padding: 0.75rem 1rem;
    border: 1px solid var(--border-color);
    border-radius: var(--radius);
    font-size: 0.95rem;
    transition: var(--transition);
    box-sizing: border-box;
}

.cosign-form-row input:focus,
.cosign-form-row select:focus,
.cosign-form-row textarea:focus {
    outline: none;
    border-color: var(--primary-color);
    box-shadow: 0 0 0 3px rgba(0, 0, 102, 0.1);
}

.cosign-form-row textarea {
    min-height: 120px;
    resize: vertical;
}

.cosign-form-grid {
    display: grid;
    grid-template-columns: repeat(2, 1fr);
    gap: 1.5rem;
}

.cosign-btn {
    padding: 0.75rem 1.5rem;
    border: none;
    border-radius: var(--radius);
    font-weight: 600;
    font-size: 0.95rem;
    cursor: pointer;
    transition: var(--transition);
    text-decoration: none;
    display: inline-flex;
    align-items: center;
    gap: 0.5rem;
}

.cosign-btn.primary {
    background: var(--secondary-color);
    color: white;
}

.cosign-btn.secondary {
    background: #6c757d;
    color: white;
}

.cosign-btn:hover {
    opacity: 0.9;
}

.required-field::after {
    content: " *";
    color: #ef4444;
}

.cosign-form-actions {
    display: flex;
    justify-content: flex-end;
    gap: 1rem;
    margin-top: 2rem;
    padding-top: 2rem;
    border-top: 1px solid var(--border-color);
}

.message {
    padding: 1rem;
    border-radius: var(--radius);
    margin-bottom: 1.5rem;
    display: none;
}

.message.success {
    background: #dcfce7;
    color: #15803d;
    border: 1px solid #86efac;
    display: block;
}

.message.error {
    background: #fee2e2;
    color: #991b1b;
    border: 1px solid #fca5a5;
    display: block;
}
</style>

<div class="wrap cosign-wrap">
    <div class="cosign-header">
        <h1><i class="fas fa-user-tag"></i> <?php echo $is_edit ? 'Edit Lead' : 'Add New Lead'; ?></h1>
        <a href="<?php echo admin_url('admin.php?page=cosign-pipeline&tab=leads'); ?>" class="cosign-btn secondary">
            <i class="fas fa-arrow-left"></i> Back to Pipeline
        </a>
    </div>

    <div class="cosign-form">
        <div id="message" class="message"></div>
        
        <form id="lead-details-form">
            <?php wp_nonce_field('cosign_nonce', 'cosign_nonce'); ?>
            <input type="hidden" name="lead_id" id="lead-id" value="<?php echo $is_edit ? esc_attr($lead_id) : ''; ?>">
            
            <h2 style="color: var(--primary-color); margin-bottom: 1.5rem; border-bottom: 2px solid var(--secondary-color); padding-bottom: 0.5rem;">
                Lead Information <span class="required-field"></span>
            </h2>

            <div class="cosign-form-grid">
                <div class="cosign-form-row">
                    <label for="generated-by" class="required-field">Lead Generated By</label>
                    <select id="generated-by" name="generated_by" required>
                        <option value="">Select Lead Generated By</option>
                        <?php foreach ($users as $user): ?>
                            <option value="<?php echo esc_attr($user['ID']); ?>" <?php selected($is_edit && $lead->generated_by == $user['ID']); ?>>
                                <?php echo esc_html($user['display_name']); ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </div>

                <div class="cosign-form-row">
                    <label for="client-name" class="required-field">Company Name</label>
                    <input type="text" id="client-name" name="client_name" value="<?php echo $is_edit ? esc_attr($lead->client_name) : ''; ?>" required>
                </div>

                <div class="cosign-form-row">
                    <label for="client-type" class="required-field">Client Type</label>
                    <select id="client-type" name="client_type" required>
                        <option value="">Select Client Type</option>
                        <option value="Sign Maker" <?php selected($is_edit && $lead->client_type == 'Sign Maker'); ?>>Sign Maker</option>
                        <option value="Printer" <?php selected($is_edit && $lead->client_type == 'Printer'); ?>>Printer</option>
                        <option value="Ad Agency" <?php selected($is_edit && $lead->client_type == 'Ad Agency'); ?>>Ad Agency</option>
                    </select>
                </div>

                <div class="cosign-form-row">
                    <label for="contact-person">Contact Person</label>
                    <input type="text" id="contact-person" name="contact_person" value="<?php echo $is_edit ? esc_attr($lead->contact_person ?? '') : ''; ?>">
                </div>

                <div class="cosign-form-row">
                    <label for="email" class="required-field">Email</label>
                    <input type="email" id="email" name="email" value="<?php echo $is_edit ? esc_attr($lead->email ?? '') : ''; ?>" required>
                </div>

                <div class="cosign-form-row">
                    <label for="phone">Phone</label>
                    <input type="tel" id="phone" name="phone" value="<?php echo $is_edit ? esc_attr($lead->phone ?? '') : ''; ?>">
                </div>
            </div>

            <h2 style="color: var(--primary-color); margin: 2rem 0 1.5rem; border-bottom: 2px solid var(--secondary-color); padding-bottom: 0.5rem;">
                Address Information
            </h2>

            <div class="cosign-form-grid">
                <div class="cosign-form-row">
                    <label for="country">Country</label>
                    <select id="country" name="country">
                        <option value="India" <?php selected($is_edit && ($lead->country ?? '') == 'India'); ?>>India</option>
                    </select>
                </div>

                <div class="cosign-form-row">
                    <label for="zone">Zone</label>
                    <select id="zone" name="zone">
                        <option value="">Select Zone</option>
                        <option value="north" <?php selected($is_edit && ($lead->zone ?? '') == 'north'); ?>>North</option>
                        <option value="south" <?php selected($is_edit && ($lead->zone ?? '') == 'south'); ?>>South</option>
                        <option value="east" <?php selected($is_edit && ($lead->zone ?? '') == 'east'); ?>>East</option>
                        <option value="west" <?php selected($is_edit && ($lead->zone ?? '') == 'west'); ?>>West</option>
                    </select>
                </div>

                <div class="cosign-form-row">
                    <label for="state">State</label>
                    <input type="text" id="state" name="state" value="<?php echo $is_edit ? esc_attr($lead->state ?? '') : ''; ?>">
                </div>

                <div class="cosign-form-row">
                    <label for="city">City</label>
                    <input type="text" id="city" name="city" value="<?php echo $is_edit ? esc_attr($lead->city ?? '') : ''; ?>">
                </div>

                <div class="cosign-form-row" style="grid-column: 1 / -1;">
                    <label for="address">Address</label>
                    <textarea id="address" name="address"><?php echo $is_edit ? esc_textarea($lead->address ?? '') : ''; ?></textarea>
                </div>
            </div>

            <div class="cosign-form-actions">
                <button type="button" class="cosign-btn secondary" onclick="window.location.href='<?php echo admin_url('admin.php?page=cosign-pipeline&tab=leads'); ?>'">
                    <i class="fas fa-times"></i> Cancel
                </button>
                <button type="submit" class="cosign-btn primary">
                    <i class="fas fa-save"></i> <?php echo $is_edit ? 'Update' : 'Save'; ?> Lead
                </button>
            </div>
        </form>
    </div>
</div>

<script>
jQuery(document).ready(function($) {
    $('#lead-details-form').on('submit', function(e) {
        e.preventDefault();

        const formData = {
            lead_id: $('#lead-id').val(),
            generated_by: $('#generated-by').val(),
            client_name: $('#client-name').val(),
            client_type: $('#client-type').val(),
            contact_person: $('#contact-person').val(),
            email: $('#email').val(),
            phone: $('#phone').val(),
            country: $('#country').val(),
            zone: $('#zone').val(),
            state: $('#state').val(),
            city: $('#city').val(),
            address: $('#address').val()
        };

        const submitBtn = $(this).find('button[type="submit"]');
        const originalText = submitBtn.html();
        submitBtn.prop('disabled', true).html('<i class="fas fa-spinner fa-spin"></i> Saving...');

        $.ajax({
            url: cosignData.ajaxUrl,
            type: 'POST',
            data: {
                action: 'cosign_save_lead',
                nonce: $('#cosign_nonce').val(),
                lead_data: formData
            },
            success: function(response) {
                if (response.success) {
                    showMessage('success', response.data.message || 'Lead saved successfully!');
                    setTimeout(function() {
                        window.location.href = '<?php echo admin_url('admin.php?page=cosign-pipeline&tab=leads'); ?>';
                    }, 1500);
                } else {
                    showMessage('error', response.data || 'Failed to save lead. Please try again.');
                    submitBtn.prop('disabled', false).html(originalText);
                }
            },
            error: function() {
                showMessage('error', 'An error occurred. Please try again.');
                submitBtn.prop('disabled', false).html(originalText);
            }
        });
    });

    function showMessage(type, message) {
        const messageDiv = $('#message');
        messageDiv.removeClass('success error').addClass(type).text(message).show();
        setTimeout(function() {
            messageDiv.fadeOut();
        }, 5000);
    }
});
</script>