<?php
if (!defined('ABSPATH')) {
    exit; // Exit if accessed directly
}

// Get current page number
$page = isset($_GET['paged']) ? max(1, intval($_GET['paged'])) : 1;

// Get number of entries per page
$per_page = isset($_GET['entries']) ? intval($_GET['entries']) : 10;

// Get search term
$search = isset($_GET['search']) ? sanitize_text_field($_GET['search']) : '';

// Initialize database connection
global $wpdb;

// Get leads data
$table = $wpdb->prefix . 'pipeline_leads';
$where = '';
if (!empty($search)) {
    $where = $wpdb->prepare(
        "WHERE company_name LIKE %s 
        OR client_type LIKE %s 
        OR generated_by LIKE %s",
        '%' . $wpdb->esc_like($search) . '%',
        '%' . $wpdb->esc_like($search) . '%',
        '%' . $wpdb->esc_like($search) . '%'
    );
}

$offset = ($page - 1) * $per_page;
$query = "SELECT * FROM {$table} {$where} ORDER BY created_date DESC LIMIT %d OFFSET %d";
$count_query = "SELECT COUNT(*) FROM {$table} {$where}";

$total_items = $wpdb->get_var($count_query);
$items = $wpdb->get_results($wpdb->prepare($query, $per_page, $offset));
$total_pages = ceil($total_items / $per_page);
?>

<div class="wrap">
    <div class="cosign-header">
        <h1><?php echo esc_html(get_admin_page_title()); ?></h1>
        <div class="header-actions">
            <button type="button" class="button-primary" onclick="openAddForm()">
                <?php _e('Add New Lead', 'cosign-planner'); ?>
            </button>
        </div>
    </div>

    <div class="pipeline-controls">
        <div class="entries-control">
            <label>Show 
                <select id="entries-count" onchange="updateEntries(this.value)">
                    <?php $entries_options = array(10, 25, 50, 100); ?>
                    <?php foreach ($entries_options as $option): ?>
                        <option value="<?php echo $option; ?>" <?php selected($per_page, $option); ?>>
                            <?php echo $option; ?>
                        </option>
                    <?php endforeach; ?>
                </select>
                entries
            </label>
        </div>
        <div class="search-control">
            <form method="get" action="" id="search-form">
                <input type="hidden" name="page" value="<?php echo esc_attr($_GET['page']); ?>">
                <input type="hidden" name="entries" value="<?php echo esc_attr($per_page); ?>">
                <label>Search: 
                    <input type="text" name="search" value="<?php echo esc_attr($search); ?>" 
                           placeholder="Search..." onkeyup="handleSearch(this)">
                </label>
            </form>
        </div>
    </div>

    <div class="pipeline-table-container">
        <table class="pipeline-table">
            <thead>
                <tr>
                    <th>Sr.No.</th>
                    <th>Company Name</th>
                    <th>Client Type</th>
                    <th>Generated By</th>
                    <th>Created Date</th>
                    <th>Status</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
            <?php
            if (!empty($items)) {
                $counter = ($page - 1) * $per_page + 1;
                foreach ($items as $item) {
                    echo '<tr>';
                    echo '<td>' . $counter++ . '</td>';
                    echo '<td>' . esc_html($item->company_name) . '</td>';
                    echo '<td>' . esc_html($item->client_type) . '</td>';
                    echo '<td>' . esc_html($item->generated_by) . '</td>';
                    echo '<td>' . esc_html(date('d-m-Y H:i', strtotime($item->created_date))) . '</td>';
                    echo '<td>' . esc_html($item->status) . '</td>';
                    echo '<td class="action-buttons">';
                    printf('
                        <button class="btn edit" onclick="editLead(%d)">Edit</button>
                        <button class="btn view" onclick="viewLead(%d)">View</button>
                        <button class="btn add-comment" onclick="addComment(%d)">Add Comment</button>
                        <button class="btn comment-history" onclick="viewCommentHistory(%d)">Comment History</button>
                        <button class="btn delete" onclick="deleteLead(%d)">Delete</button>',
                        esc_js($item->id),
                        esc_js($item->id),
                        esc_js($item->id),
                        esc_js($item->id),
                        esc_js($item->id)
                    );
                    echo '</td>';
                    echo '</tr>';
                }
            } else {
                echo '<tr><td colspan="7" class="no-records">No records found</td></tr>';
            }
            ?>
            </tbody>
        </table>
    </div>

    <?php if ($total_pages > 1): ?>
    <div class="pipeline-pagination">
        <div class="pagination-controls">
            <?php
            if ($page > 1) {
                printf(
                    '<a href="%s" class="btn-page">«</a>',
                    esc_url(add_query_arg('paged', $page - 1))
                );
            }
            
            for ($i = 1; $i <= $total_pages; $i++) {
                printf(
                    '<a href="%s" class="btn-page %s">%d</a>',
                    esc_url(add_query_arg('paged', $i)),
                    $i === $page ? 'active' : '',
                    $i
                );
            }
            
            if ($page < $total_pages) {
                printf(
                    '<a href="%s" class="btn-page">»</a>',
                    esc_url(add_query_arg('paged', $page + 1))
                );
            }
            ?>
        </div>
    </div>
    <?php endif; ?>

    <?php include_once dirname(__FILE__) . '/lead-form.php'; ?>
</div>

<?php
// Add nonce for security
$nonce = wp_create_nonce('pipeline_actions_nonce');
?>
<script>
<?php include_once dirname(__FILE__) . '/js/leads.js'; ?>
</script>

<style>
<?php include_once dirname(__FILE__) . '/css/pipeline.css'; ?>
</style>