<?php
if (!defined('ABSPATH')) {
    exit; // Exit if accessed directly
}
?>
<div class="pipeline-table-container">
    <table class="pipeline-table">
        <thead>
            <tr>
                <?php
                echo '<th>Sr.No.</th>';
                
                if ($tab === 'sales') {
                    echo '<th>Quotation Number</th>';
                    echo '<th>Date of Quotation</th>';
                    echo '<th>Client Name</th>';
                    echo '<th>Project</th>';
                    echo '<th>Project Type</th>';
                    echo '<th>Project Value</th>';
                    echo '<th>Conversion Belief</th>';
                    echo '<th>Time Belief</th>';
                } elseif ($tab === 'leads') {
                    echo '<th>Client Name</th>';
                    echo '<th>Client Type</th>';
                    echo '<th>Generated By</th>';
                    echo '<th>Created Date</th>';
                } else {
                    echo '<th>Project Name</th>';
                    echo '<th>Generated By</th>';
                    echo '<th>Created Date</th>';
                    echo '<th>Stakeholder List</th>';
                }
                
                echo '<th>Action</th>';
                ?>
            </tr>
        </thead>
        <tbody>
        <?php
        if (!empty($data['items'])) {
            $counter = ($page - 1) * $per_page + 1;
            foreach ($data['items'] as $item) {
                echo '<tr>';
                echo '<td>' . $counter++ . '</td>';
                    
                if ($tab === 'sales') {
                    echo '<td>' . esc_html($item->quotation_number) . '</td>';
                    echo '<td>' . esc_html(date('d-m-Y', strtotime($item->quotation_date))) . '</td>';
                    echo '<td>' . esc_html($item->client_name) . '</td>';
                    echo '<td>' . esc_html($item->project) . '</td>';
                    echo '<td>' . esc_html($item->project_type) . '</td>';
                    echo '<td>' . esc_html($item->project_value) . '</td>';
                    echo '<td>' . esc_html($item->conversion_belief) . '%</td>';
                    echo '<td>' . esc_html($item->time_belief) . '%</td>';
                } elseif ($tab === 'leads') {
                    echo '<td>' . esc_html($item->client_name) . '</td>';
                    echo '<td>' . esc_html($item->client_type) . '</td>';
                    echo '<td>' . esc_html($item->generated_by) . '</td>';
                    echo '<td>' . esc_html(date('d-m-Y H:i', strtotime($item->created_date))) . '</td>';
                } else {
                    echo '<td>' . esc_html($item->project_name) . '</td>';
                    echo '<td>' . esc_html($item->generated_by) . '</td>';
                    echo '<td>' . esc_html(date('d-m-Y H:i', strtotime($item->created_date))) . '</td>';
                    echo '<td>' . esc_html($item->stakeholders) . '</td>';
                }
                
                echo '<td class="action-buttons">';
                if ($tab === 'sales') {
                    printf('
                        <button class="btn generate-pi" onclick="generatePI(%d)">Generate PI</button>
                        <button class="btn generate-po" onclick="generatePO(%d)">Generate PO</button>
                        <button class="btn view" onclick="viewItem(%d)">View</button>
                        <button class="btn edit" onclick="editItem(%d)">Edit</button>
                        <button class="btn confirm" onclick="confirmItem(%d)">Confirm</button>
                        <button class="btn delete" onclick="deleteItem(%d)">Delete</button>',
                        esc_js($item->id),
                        esc_js($item->id),
                        esc_js($item->id),
                        esc_js($item->id),
                        esc_js($item->id),
                        esc_js($item->id)
                    );
                } else {
                    printf('
                        <button class="btn pipeline-guide" onclick="pipelineGuide(%d)">Pipeline Guide</button>
                        <button class="btn add-comment" onclick="addComment(%d)">Add Comment</button>
                        <button class="btn comment-history" onclick="viewCommentHistory(%d)">Comment History</button>
                        <button class="btn delete" onclick="deleteItem(%d)">Delete</button>',
                        esc_js($item->id),
                        esc_js($item->id),
                        esc_js($item->id),
                        esc_js($item->id)
                    );
                }
                echo '</td>';
                echo '</tr>';
            }
        } else {
            $colspan = $tab === 'sales' ? '10' : ($tab === 'leads' ? '5' : '6');
            echo '<tr><td colspan="' . $colspan . '" class="no-records">No records found</td></tr>';
        }
        ?>
        </tbody>
    </table>
</div>

<?php if ($data['total_pages'] > 1): ?>
<div class="pipeline-pagination">
    <div class="pagination-controls">
        <?php
        if ($page > 1) {
            echo '<button class="btn-page" onclick="changePage(' . ($page - 1) . ')">«</button>';
        }
        
        for ($i = 1; $i <= $data['total_pages']; $i++) {
            printf(
                '<button class="btn-page %s" onclick="changePage(%d)">%d</button>',
                $i === $page ? 'active' : '',
                $i,
                $i
            );
        }
        
        if ($page < $data['total_pages']) {
            echo '<button class="btn-page" onclick="changePage(' . ($page + 1) . ')">»</button>';
        }
        ?>
    </div>
</div>
<?php endif; ?>